### ISSUE TITLE
100% should equal 0 HP, but isn't always the case

### ISSUE THREAD

**Issue by GambetTV** [oOve/destructibles#2]
I have this set up so that tokens switch to an unconscious/dying token at 0 HP, which shows them laying on their back. So I set this module to swap at 100%. Unfortunately there must be some kind of rounding error, because if my token has 58 health and I deal 57 damage to them, they still switch. Could be cool if you don't have it rounding the numbers, or at least make sure that 100% damage means 0 HP.

**Comment by GambetTV** [comment]
Actually strike that, I don't understand the math of this at all. If I set it to 100% it swaps tokens even if I deal 1 point of damage.

**Comment by GambetTV** [comment]
Okay, sorry for all the comments, the module is very confusing. The language on it is very confusing. The module reads "at ___ Dmg" but I think what you mean for it to say is "at ___ HP." If I set it to 10, and my token has 100 HP, the token won't switch until it drops below 10 HP. So at 10% HP it drops. 10% damage makes it seem like it's only taken 10 damage, not 90. Very confusing!

Also, if you set it to 100% the token doesn't change until you drop below 100%. And if you set it to 0% it NEVER changes. It should definitely change if it's set to 0%.

I suspect the issue is that you have it set to change if it drops below the number, but what you should have it say is if the number is below than or EQUAL TO, then it should fire off. Does that make sense?

Love the module! Again, sorry for the spam messages!

**Comment by oOve** [comment]
Thank you, no worries on the "spam". I should make the text clearer yes :D 
The at is a percentage. By default it uses the regular token image, 
It won't switch image until it passes below the percentage. If you set it to 100%, it won't show that image until it drops below 100. 
The same with zero, it won't change until it goes "past" 0%.

I agree that this might not be the most intuitive way, so I will change it to be "below or equal".
I will close this issue once that is implemented.

**Comment by oOve** [comment]
Fixed issue. Added a % sign next to the "at", and changed the algorithm to swap the image when its "at or below" the given percentage.
